# Generated by Django 5.1.4 on 2025-01-01 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='image',
            field=models.ImageField(default='uploads/product/default.jpg', upload_to='uploads/product/'),
        ),
    ]
