# Generated by Django 5.1.4 on 2025-01-01 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_laptop_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='image',
            field=models.ImageField(default='product/default.jpg', upload_to='product/'),
        ),
    ]
